"""PaikdabangMenuDocument migration

Revision ID: 3d0d1afd74fb
Revises: 4c15bc2f0b3d
Create Date: 2025-02-20 14:31:08.399346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from config import settings


# revision identifiers, used by Alembic.
revision: str = '3d0d1afd74fb'
down_revision: Union[str, None] = '4c15bc2f0b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paikdabangmenudocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=settings.EMBEDDING_DIMENSIONS), nullable=True),
    sa.Column('page_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('paikdabang_menu_document_embedding_idx', 'paikdabangmenudocument', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('paikdabang_menu_document_embedding_idx', table_name='paikdabangmenudocument', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('paikdabangmenudocument')
    # ### end Alembic commands ###
