"""tax migration

Revision ID: 468d3b1c0505
Revises: 3d0d1afd74fb
Create Date: 2025-02-21 10:32:24.343198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from config import settings

# revision identifiers, used by Alembic.
revision: str = '468d3b1c0505'
down_revision: Union[str, None] = '3d0d1afd74fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxlawdocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.halfvec.HALFVEC(dim=settings.EMBEDDING_DIMENSIONS), nullable=True),
    sa.Column('page_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tax_law_document_embedding_idx', 'taxlawdocument', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'halfvec_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tax_law_document_embedding_idx', table_name='taxlawdocument', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'halfvec_cosine_ops'})
    op.drop_table('taxlawdocument')
    # ### end Alembic commands ###
